### ISSUE TITLE
Parser Error: Could not find type "ImGuiFont" in the current scope.

### ISSUE THREAD

**Issue by yahkr** [pkdawson/imgui-godot#72]
Triggers when launching game within editor.  When a C# code change takes place, after first error launching again works fine.  Using "imgui-godot-6.0.1-csharp-only.zip" on Godot 4.3.beta2.mono

Specifically this happens after c# code change and the use of "Run Project hotkey". Works fine if you Build project and then use hotkey

on line 4 of ImGuiConfig.gd:
```gdscript
@export var Fonts: Array[ImGuiFont]
```

**Comment by pkdawson** [comment]
Those two simple resource scripts are a self-contained unit, they don't depend on anything else, so this is almost certainly a Godot bug.

But good news, [a PR](https://github.com/godotengine/godot/pull/92303) was just merged to address similar issues, and that fix will be in 4.3-beta3.

**Comment by pkdawson** [comment]
Should be fixed upstream in 4.3.0.

**Comment by Tichau** [comment]
The issue is still present in version v4.3.stable.mono.official [77dcf97d8].
I'm using ImGui v6.2.1

Thanks for your work on ImGui !

**Comment by pkdawson** [comment]
Alright, there's a workaround I can try. I'm pretty sure it'll work but this is basically impossible to test. It'll be in the next release.

**Comment by Tichau** [comment]
Also, I can only reproduce this issue on Windows. On my linux laptop there is no issue.

**Comment by jasonswearingen** [comment]
I'm also seeing this problem, but it is intermittent, I don't think it's related to build changes, it just fails occasionally.   I have kind of a weird [Tool] based setup but I'm seeing some other weird frame stalls also, so I will try doing some more debugging.   If anyone else has additional details to share, please do.

**Comment by jasonswearingen** [comment]
this does appear to be an upstream/godot issue: https://github.com/godotengine/godot/issues/82392

**Comment by pkdawson** [comment]
Sorry, I committed a workaround last month, but I haven't tagged a new release yet. I'll do that today or tomorrow.

**Comment by pkdawson** [comment]
Fix released in v6.3.0. Let me know if you still encounter similar errors.
